on:
  push:
    branches: [master]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      id: example
    - name: Show action_path_inline
      run: echo "The action path is '${{ steps.example.outputs.action_path_inline }}'"
    - name: Show action_path_step
      run: echo "The action path is '${{ steps.example.outputs.action_path_step }}'"
